### ISSUE TITLE
too big

### ISSUE THREAD

**Issue by timoxley** [gratipay/gratipay-badge#1]
Nice, but the badge is a bit too big. Please make this the same/similar height as other common badges:

Compare:

[![Support via Gittip](https://rawgithub.com/twolfson/gittip-badge/0.1.0/dist/gittip.png)](https://www.gittip.com/USERNAME/)[![Build Status](https://travis-ci.org/timoxley/cruft.png?branch=master)](https://travis-ci.org/timoxley/cruft)[![Build Status](https://nodei.co/npm/readable-stream.png?mini=true)](https://travis-ci.org/timoxley/cruft)[![Flattr this!](https://api.flattr.com/button/flattr-badge-large.png)](https://flattr.com/submit/auto?user_id=hughskennedy&url=http://github.com/hughsk/markdown-tree&title=markdown-tree&description=hughsk/markdown-tree%20on%20GitHub&language=en_GB&tags=flattr,github,javascript&category=software)[![experimental](http://hughsk.github.io/stability-badges/dist/experimental.svg)](http://github.com/hughsk/stability-badges)

**Comment by twolfson** [comment]
The intent was to be a large badge. `gittip` has a smaller badge which I used for a while but I wanted something more visible. You should check it out:

http://shields.io/  (second image)
