### ISSUE TITLE
Smaller badge

### ISSUE THREAD

**Issue by PeterDaveHello** [gratipay/gratipay-badge#13]
I wonder if you would like to have a smaller version, current badge is a little large compare to other common badges on GitHub. Thank.

**Comment by twolfson** [comment]
We explored this a little in the `dev/explore.smaller.badge` branch:

https://github.com/gratipay/gratipay-badge/tree/c4a49005c4b17d178b55243a28e72ddf0cc3f6c5

However, even more consistent badges can be found on shields.io:

http://shields.io/

I have seen some people use the custom text too (e.g. Remy Sharp has a shields in the upper right of his blog): https://remysharp.com/2015/10/14/the-art-of-debugging

Do any of those work or did you have something else in mind?

**Comment by PeterDaveHello** [comment]
gratipay dose, I just wonder if there is an official version of that kind of badge? 
Thanks for your prompt reply!

**Comment by twolfson** [comment]
I'm not sure what you are referring to by "that kind of badge". Which one was it?

**Comment by PeterDaveHello** [comment]
Sorry, the style and size.

**Comment by twolfson** [comment]
That's still a little ambiguous =/ Which one of these 3 links:
- https://github.com/gratipay/gratipay-badge/tree/c4a49005c4b17d178b55243a28e72ddf0cc3f6c5
- http://shields.io/
- https://remysharp.com/2015/10/14/the-art-of-debugging

**Comment by PeterDaveHello** [comment]
hmmmm ... how to say that? official version of this size? [![Gratipay](https://img.shields.io/gratipay/JSFiddle.svg)]()
Sorry that my English is not so good, sometimes didn't find a good term to describe the problem.

**Comment by PeterDaveHello** [comment]
To be precise, the high should be 20px.

**Comment by twolfson** [comment]
Ah, k. Gratipay already has badges on shields.io (e.g. the one you linked). And if I recall correctly, shields.io was built out by a good chunk of the Gratipay team.

That being said, here's a one-off badge that I think fits your requisites using the form at the bottom of shields.io:

https://img.shields.io/badge/support%20via-gratipay-green.svg

![support via gratipay](https://img.shields.io/badge/support%20via-gratipay-green.svg)

I don't believe anything official in that size/style belongs in this repo per se. It feels like that should live in shields.io (maybe with a link/image in the README here).

**Comment by PeterDaveHello** [comment]
Okay, thanks!
