### ISSUE TITLE
Still using the 'Gittip' branding in the repository description

### ISSUE THREAD

**Issue by jacquerie** [gratipay/gratipay-badge#7]
![gratipay_gratipay-badge](https://cloud.githubusercontent.com/assets/381280/4606799/65634538-5231-11e4-8a81-6e2f775ebfdd.jpg)

**Comment by seanlinsley** [comment]
Thanks for pointing that out! I just updated it.

![screen shot 2014-10-12 at 12 24 45 pm](https://cloud.githubusercontent.com/assets/688886/4606878/bb3389ca-5234-11e4-94d1-bea5401edf3d.png)

**Comment by twolfson** [comment]
Nice catch! I guess `git grep` can't find everything =/
